import { validate } from "../middleware/validate.js";
import { cartSchema } from "../validators/marketplaceValidator.js";import express from "express";
import { getCart, addToCart, updateCart, removeFromCart, clearCart } from "../controllers/cartController.js";
import { protect } from "../middleware/authMiddleware.js";
const router = express.Router();
router.get("/", protect, getCart);
router.post("/add", protect, validate(cartSchema), addToCart);
router.put("/update", protect, validate(cartSchema), updateCart);
router.delete("/remove/:productId", protect, removeFromCart);
router.delete("/clear", protect, clearCart);
export default router;
