import express from "express";
import { createCoupon, getCoupons, updateCoupon, deleteCoupon, validateCouponEndpoint } from "../controllers/couponController.js";
import { protect } from "../middleware/authMiddleware.js";
import { authorize } from "../middleware/roleMiddleware.js";
const router = express.Router();
router.post("/validate", protect, validateCouponEndpoint);
router.get("/", protect, authorize("admin"), getCoupons);
router.post("/", protect, authorize("admin"), createCoupon);
router.put("/:id", protect, authorize("admin"), updateCoupon);
router.delete("/:id", protect, authorize("admin"), deleteCoupon);
export default router;
